steps:
  - name: python:3.8
    entrypoint: pip
    args:
      [
        "install",
        "--user",
        "flake8",
        "flake8",
        "flake8-docstrings",
        "flake8-quotes",
        "flake8-bugbear",
      ]
  - name: python:3.8
    entrypoint: python
    args: ["-m", "flake8"]
