version: "3.7"
services:
  cloud_build_sample:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: cloud_build_sample-image
    container_name: cloud_build_sample-container
    tty: true
